; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:umbulan-monitor]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_port = /dev/cu.usbmodem1101
upload_port = /dev/cu.usbmodem1101
upload_speed = 921600

board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    mobizt/FirebaseClient @ ^2.2.9
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
